name: C CI Docker Makefile

on:
  push:
    branches:
      - 'main'
      - 'dev'
  pull_request:
    branches:
      - 'main'
      - 'dev'
      
# Define the image tag
env:
  #IMAGE_TAG: jamiehollandimi/myimagename:latest
  DOCKER_IMAGE: gitdocker:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v3
    - name: Build the Docker image
      #run: docker build . --file Dockerfile --tag "${IMAGE_TAG}"
      run: docker build . --file Dockerfile --tag $DOCKER_IMAGE
    - name: Build the project
      run: docker run -td $DOCKER_IMAGE
    #- name: Run Make
      #run: make -j8 all
      #working-directory: /github/workspace/Build/
      
    #- name: Find all Hex files and fail if found
      #uses: DovnarAlexander/github-action-file-detection@master
      #with:
        #wildcard: '*.exe'
        #base_path: '/'
        
    #- name: Upload Elf and Hex file from Docker Image
      #uses: actions/upload-artifact@v3
      #with:
        #name: BuildFiles
        #path: |
          #/Build/*.hex
          #/Build/*.elf
        #retention-days: 1
    - name: Removes the Docker Container
      run: docker run --rm $DOCKER_IMAGE
