name: C CI Docker Makefile

on:
  push:
    branches:
      - 'main'
      - 'dev'
  pull_request:
    branches:
      - 'main'
      - 'dev'
      
# Define the image tag
env:
  DOCKER_IMAGE: jamiehollandimi/gitdocker:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $DOCKER_IMAGE
        
    - name: Build the Docker container
      run: docker run --rm $DOCKER_IMAGE
    - uses: shrink/actions-docker-extract@v2
      with:
        image: $DOCKER_IMAGE
        path: "Build/."
    #- name: Extract files from Docker Image
      #uses: shrink/actions-docker-extract@v2
      #id: extract
      #with:
        #image: $DOCKER_IMAGE
        #path: stm32_executable.hex
    #- name: Upload Elf and Hex file from Docker Image
      #uses: actions/upload-artifact@v3
      #with:
        #name: BuildFiles
        #path: ${{ steps.extract.outputs.destination }}
        #retention-days: 1
        
    #- name: Upload Elf and Hex file from Docker Image
      #uses: actions/upload-artifact@v3
      #with:
        #name: BuildFiles
        #path: |
          #/Build/*.hex
          #/Build/*.elf
        #retention-days: 1
        
    #- name: Find all Hex files and fail if found
      #uses: DovnarAlexander/github-action-file-detection@master
      #with:
        #wildcard: '*.elf'
        #exit_code_found: 1
        #exit_code_not_found: 0
        #base_path: './'     
        
    #- name: Removes the Docker Container
      #run: docker --rm $DOCKER_IMAGE
