name: C CI Docker Makefile

on:
  push:
    branches:
      - 'main'
      - 'dev'
  pull_request:
    branches:
      - 'main'
      - 'dev'
  workflow_dispatch:
  
# Define the image tag
# ${{ github.repository }} is the repository name
# IMAGE_TAG must be lowercase
env:
  REGISTRY: ghcr.io
  #IMAGE_NAME: ${{ lowercase(github.repository) }}
  #USER_NAME: ${{ lowercase(github.actor) }}
  #VERSION: ${{ lowercase(github.sha) }}
  #IMAGE_TAG: $(REGISTRY)/$(USER_NAME)/$(IMAGE_NAME):$(VERSION)
  IMAGE_TAG: ghcr.io/jamie-holland-imi/project-name:latest

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - name: checkout repository
      uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2.2.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag $IMAGE_TAG
        docker run $IMAGE_TAG
        docker push $IMAGE_TAG   
    
  compile:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jamie-holland-imi/project-name:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      packages: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        
      - name: Run the Makefile and Build the Project
        run: |
          make
          ls
          pwd
      - name: Publish Artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: build_files
          path: |
            ./*.elf
            ./*.hex
          retention-days: 1
          if-no-files-found: error
