name: C CI Docker Makefile

on:
  push:
    branches:
      - 'main'
      - 'dev'
  pull_request:
    branches:
      - 'main'
      - 'dev'
  workflow_dispatch:
  
# Define the image tag
# ${{ github.repository }} is the repository name
# IMAGE_TAG must be lowercase
env:
  REGISTRY: ghcr.io
  REPO_NAME: ${{ github.event.repository.name }}
  USER_NAME: ${{ github.actor }}
  VERSION: "latest"
  IMAGE_TAG: $REGISTRY"/"$USER_NAME"/"$REPO_NAME":"$VERSION
  #IMAGE_TAG: ghcr.io/jamie-holland-imi/project-name:latest

jobs:
  initialization:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.set_image.outputs.image }}
    steps:
      - id: set_image
        run: echo "{image}={${{env.IMAGE_TAG}}}" >> $GITHUB_OUTPUT
  build:
    runs-on: ubuntu-latest
    needs: initialization
    permissions:
      packages: write
    steps:
    - name: checkout repository
      uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2.2.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ${{ needs.initialization.outputs.image }}
        docker run ${{ needs.initialization.outputs.image }}
        docker push ${{ needs.initialization.outputs.image }}
    
  compile:
    needs: 
      - build 
      - initialization
    runs-on: ubuntu-latest
    container:
      image: ${{ needs.initialization.outputs.image }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      packages: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        
      - name: Run the Makefile and Build the Project
        run: |
          make
          ls
          pwd
      - name: Publish Artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: build_files
          path: |
            ./*.elf
            ./*.hex
          retention-days: 1
          if-no-files-found: error
