name: C CI Docker Makefile

on:
  push:
    branches:
      - 'main'
      - 'dev'
  pull_request:
    branches:
      - 'main'
      - 'dev'
      
# Define the image tag
#env:
  #IMAGE_TAG: jamiehollandimi/myimagename:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository files
    - name: checkout repo
      uses: actions/checkout@v3
      # Build the hello world image
    - name: Build the Docker image
      #run: docker build . --file Dockerfile --tag "${IMAGE_TAG}"
      run: docker build . --file Dockerfile --tag gitdocker:latest
    - name: Build the project
      run: docker run --rm gitdocker:latest
    - name: Upload Elf and Hex file from Docker Image
      uses: actions/upload-artifact@v3
      with:
        name: BuildFiles
        path: |
          ./build/BasicButtonPress.hex
          ./build/BasicButtonPress.elf
        retention-days: 1
