name: CI CD C Docker Makefile

on:
  push:
    branches:
      - 'main'
      - 'dev'
  pull_request:
    branches:
      - 'main'
      - 'dev'
  workflow_dispatch:
  
# Define the image tag
# The IMAGE_TAG must be lowercase the ,, convert to lowercase
env:
  REGISTRY: ghcr.io
  REPO_NAME: ${{ github.event.repository.name }}
  USER_NAME: ${{ github.actor }}
  VERSION: "latest"
  IMAGE_TAG: ${REGISTRY,,}"/"${USER_NAME,,}"/"${REPO_NAME,,}":"${VERSION,,}
  #example result: IMAGE_TAG: ghcr.io/jamie-holland-imi/project-name:latest

jobs:       
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - name: checkout repository
      uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2.2.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ${{env.IMAGE_TAG}}
        docker run ${{env.IMAGE_TAG}}
        docker push ${{env.IMAGE_TAG}}

  var_init:
    runs-on: ubuntu-latest
    needs: build
    outputs:
      image: ${{ steps.set_image.outputs.image }}
    steps:
      - id: set_image
        run: echo "image=${{env.IMAGE_TAG}}" >> $GITHUB_OUTPUT

  compile:
    needs: var_init
    runs-on: ubuntu-latest
    container:
      image: ${{ needs.var_init.outputs.image }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      packages: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        
      - name: Run the Makefile and Build the Project
        run: |
          make
          ls
          pwd
      - name: Publish Artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: build_files
          path: |
            ./*.elf
            ./*.hex
          retention-days: 1
          if-no-files-found: error
