name: C CI Docker Makefile

on:
  push:
    branches:
      - 'main'
      - 'dev'
  pull_request:
    branches:
      - 'main'
      - 'dev'
      
# Define the image tag
# ${{ github.repository }} repository name
env:
  DOCKER_IMAGE: ${{github.actor}}/gitdocker:latest

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - name: checkout repository
      uses: actions/checkout@v3
  
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $DOCKER_IMAGE
    - name: Build the Docker container
      run: docker run -t docker.io/$DOCKER_IMAGE
      #run: docker run --rm $REGISTRY/$IMAGE_NAME
    - name: run ls
      run: ls
    - name: run ls
      run: ls
      working-directory: ./Build
    #- name: Extract files from Docker Image
      #uses: shrink/actions-docker-extract@v2
      #id: extract
      #with:
        #image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        #path: "Build/stm32_executable.elf"        
    #- name: Upload Elf and Hex file from Docker Image
      #uses: actions/upload-artifact@v3
      #with:
        #name: BuildFiles
        #path: |
          #/Build/*.hex
          #/Build/*.elf
        #retention-days: 1
  compile:
    name: Compile site assets
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - uses: docker/build-push-action@v2
        with:
          tags: jamie-holland-imi/gitdocker:latest
          push: false
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
            image: jamie-holland-imi/gitdocker:latest
            options: -v ${{ github.workspace }}:/var/www
            run: |
              composer install
              npm install
      - name: run ls
        run: ls 
      - name: Find all Hex files and fail if found
        uses: DovnarAlexander/github-action-file-detection@master
        with:
          wildcard: '*.elf'
          exit_code_found: 1
          exit_code_not_found: 0
          base_path: '/'     
    #- name: Removes the Docker Container
      #run: docker --rm $DOCKER_IMAGE
