name: C CI Docker Makefile

on:
  push:
    branches:
      - 'main'
      - 'dev'
  pull_request:
    branches:
      - 'main'
      - 'dev'
      
# Define the image tag
env:
  DOCKER_IMAGE: jamiehollandimi/gitdocker:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $DOCKER_IMAGE
        
    - name: Build the Docker container
      run: docker run --rm $DOCKER_IMAGE
        
    #docker cp $DOCKER_IMAGE:/home/dev/Build /Build

    #- name: Run Make
      #run: make -j8 all
      #working-directory: /github/workspace/Build/
      
    - name: Find all Hex files and fail if found
      uses: DovnarAlexander/github-action-file-detection@master
      with:
        wildcard: '*.hex'
        base_path: '/'
        
    #- name: Upload Elf and Hex file from Docker Image
      #uses: actions/upload-artifact@v3
      #with:
        #name: BuildFiles
        #path: |
          #/Build/*.hex
          #/Build/*.elf
        #retention-days: 1
        
    #- name: Removes the Docker Container
      #run: docker --rm $DOCKER_IMAGE
