name: Demo

on:
  push:
    branches:
      - 'dev'
  pull_request:
    branches:
      - 'dev'
  workflow_dispatch:
  
# The IMAGE_TAG sets the docker image name, it must be lowercase the ,, convert to lowercase
env:
  REGISTRY: ghcr.io
  REPO_NAME: ${{ github.event.repository.name }}
  USER_NAME: ${{ github.actor }}
  VERSION: "latest"
  IMAGE_TAG: ${REGISTRY,,}"/"${USER_NAME,,}"/"${REPO_NAME,,}":"${VERSION,,}

jobs:
  variable_substitution:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.set_image.outputs.image }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Adds Dockerfile Version to Image Tag
      run: |
        find ./ -name 'Dockerfile' | while read filename; 
          do unixtime=$(git log -1 --format="%at" -- "${filename}"); 
          touchtime=$(date -d @$unixtime +'%Y%m%d%H%M.%S'); 
          echo "VERSION='${touchtime}'" >> $GITHUB_ENV;
        done
    - run: echo "The image " ${{env.IMAGE_TAG}}
    - run: |
        vari = $(git log -- filename ./Dockerfile --pretty=format:"%h - %t - %cd")
        echo $vari
    - id: set_image
      run: echo "image=${{env.IMAGE_TAG}}" >> $GITHUB_OUTPUT
