name: Docker Image CI

on:
  push:
    paths:
    - 'Dockerfile'
    - '.github/workflows/docker-image.yml'
  pull_request:
    paths:
    - 'Dockerfile'
    - '.github/workflows/docker-image.yml'
  workflow_dispatch:
  
env:
  REGISTRY: ghcr.io
  REPO_NAME: ${{ github.event.repository.name }}
  USER_NAME: ${{ github.actor }}
  VERSION: "latest"
  IMAGE_TAG: ${REGISTRY,,}"/"${USER_NAME,,}"/"${REPO_NAME,,}":"${VERSION,,}
  
jobs:
  build_image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2.2.0
      with:
        registry: ${{env.REGISTRY}}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build Docker Image
      run: |
        docker build . --file Dockerfile --tag ${{ env.IMAGE_TAG }}
        docker run ${{ env.IMAGE_TAG }}
        docker push ${{ env.IMAGE_TAG }}
        echo "The image " ${{ env.IMAGE_TAG }} " has been created"

