name: Docker Image CI

on:
  push:
    paths:
    - 'Dockerfile'
    - '.github/workflows/docker-image.yml'
  pull_request:
    paths:
    - 'Dockerfile'
    - '.github/workflows/docker-image.yml'
  workflow_dispatch:
  
env:
  REGISTRY: ghcr.io
  REPO_NAME: ${{ github.event.repository.name }}
  USER_NAME: ${{ github.actor }}
  ORG_NAME: ${{ github.repository_owner }}
  VERSION: "latest"
  IMAGE_TAG: ${REGISTRY,,}"/"${ORG_NAME,,}"/"${REPO_NAME,,}":"${VERSION,,}
  
jobs:
  variable_substitution:
    runs-on: ubuntu-22.04
    outputs:
      image: ${{ steps.set_image.outputs.image }}
    steps:
    - id: set_image
      run: echo "image=${{env.IMAGE_TAG}}" >> $GITHUB_OUTPUT
      
  build_image:
    needs: variable_substitution
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3.0.0
      with:
        registry: ${{env.REGISTRY}}
        username: ${ORG_NAME,,}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{needs.variable_substitution.outputs.image}}
        secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}
