name: Docker Image CI

on:
  push:
    paths:
    - 'Dockerfile'
    
env:
  REGISTRY: ghcr.io
  REPO_NAME: ${{ github.event.repository.name }}
  USER_NAME: ${{ github.actor }}
  VERSION: "latest"
  IMAGE_TAG: ${REGISTRY,,}"/"${USER_NAME,,}"/"${REPO_NAME,,}":"${VERSION,,}
  
jobs:
  build_image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2.2.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: If Docker image doesnt exist build it
      run: |
        if docker image inspect --tag ${{ env.IMAGE_TAG }} >/dev/null 2>&1; then
          echo "The image " ${{ env.IMAGE_TAG }} " already exists"
        else
          docker build . --file Dockerfile --tag ${{ env.IMAGE_TAG }}
          docker run ${{ env.IMAGE_TAG }}
          docker push ${{ env.IMAGE_TAG }}
          echo "The image " ${{ env.IMAGE_TAG }} " has been created"
        fi
