name: Project Build CI

on:
  push:
    paths:
      - '**.makefile'
      - '**.makefile'
  pull_request:
    paths:
      - '**.dockerfile'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: ghcr.io/jamie-holland-imi/project-name:latest

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker pull $IMAGE_TAG
      - name: Exit if Fails
        if: ${{ failure() }}
        run: needs.check.outputs.status == 'failure'
      - name: Success Status
        if: ${{ success() }}
        run: needs.check.outputs.status == 'success'
            
  compile:
    needs: check
    if: needs.check.outputs.status == 'success'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jamie-holland-imi/project-name:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      packages: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        
      - name: Run the Makefile and Build the Project
        run: |
          make
          ls
          pwd
      - name: Publish Artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: build_files
          path: |
            ./*.elf
            ./*.hex
          retention-days: 1
          if-no-files-found: error

