name: "Static Analysis"

on:
  push:
    branches:
      - 'static-analysis'
  workflow_dispatch:
      
env:
  REGISTRY: ghcr.io
  REPO_NAME: ${{ github.event.repository.name }}
  USER_NAME: ${{ github.actor }}
  ORG_NAME: ${{ github.repository_owner }}
  VERSION: "latest"
  IMAGE_TAG: ${REGISTRY,,}"/"${ORG_NAME,,}"/"${REPO_NAME,,}":"${VERSION,,}
  
jobs:
  variable_substitution:
    runs-on: ubuntu-20.04
    outputs:
      image: ${{ steps.set_image.outputs.image }}
    steps:
      - id: set_image
        run: echo "image=${{env.IMAGE_TAG}}" >> $GITHUB_OUTPUT

  static_analysis:
    name: static_analysis
    runs-on: ubuntu-20.04
    needs: variable_substitution
    container:
      image: ${{ needs.variable_substitution.outputs.image }}
      credentials:
        username: ${ORG_NAME,,}
        password: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: set up env var
        run: |
          git config --global --add safe.directory '*'
          echo "GIT_TAG=$(git describe --tags)" >> $GITHUB_ENV
        shell: bash
      - name: Run CppCheck
        run: |
          cppcheck --enable=all --output-file=cppcheck_report_${{ env.GIT_TAG }}.txt --file-list="./tests/cpp_files.txt" --suppressions-list="./tests/suppressions.txt" --addon="./tests/misra.json"
      - name: Run CppLint
        continue-on-error: true
        run: |
          cpplint --extensions=c --recursive="./tests/cpp_files.txt" >> cpplint_report_${{ env.GIT_TAG }}.txt 2>&1
      - name: Create Artifact
        uses: actions/upload-artifact@v3
        with:
          name: CppReports_${{ env.GIT_TAG }}
          path: |
            ./cppcheck_report_${{ env.GIT_TAG }}.txt
            ./cpplint_report_${{ env.GIT_TAG }}.txt
