name: "Static Analysis"

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:
  
env:
  REGISTRY: ghcr.io
  REPO_NAME: ${{ github.event.repository.name }}
  USER_NAME: ${{ github.actor }}
  VERSION: "latest"
  IMAGE_TAG: ${REGISTRY,,}"/"${USER_NAME,,}"/"${REPO_NAME,,}":"${VERSION,,}

jobs:
  variable_substitution:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.set_image.outputs.image }}
    steps:
      - id: set_image
        run: echo "image=${{env.IMAGE_TAG}}" >> $GITHUB_OUTPUT
        
  analyze:
    name: Analyze
    runs-on: ubuntu-latest    
    needs: variable_substitution
    container:
      image: ${{ needs.variable_substitution.outputs.image }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

# Runs code analysis with C/C++test.
    - name: Run C/C++test
      uses: parasoft/run-cpptest-action@2.0.1
      with:
        input: build/compile_commands.json
        testConfig: 'builtin://MISRA C 2012'
        compilerConfig: 'clang_10_0'
      
#    - name: Install ClangFormat
#      run: |
#        apt-get install -y clang-format
#        git config --system --add safe.directory '*'
#    - name: Run linters
#      uses: wearerequired/lint-action@v2.3.0
#      with:
#        clang_format: true
#        working-directory:: ./Core/Src/
