name: "Static Analysis"

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
# Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:
  
env:
  REGISTRY: ghcr.io
  REPO_NAME: ${{ github.event.repository.name }}
  USER_NAME: ${{ github.actor }}
  VERSION: "latest"
  IMAGE_TAG: ${REGISTRY,,}"/"${USER_NAME,,}"/"${REPO_NAME,,}":"${VERSION,,}
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  variable_substitution:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.set_image.outputs.image }}
    steps:
      - id: set_image
        run: echo "image=${{env.IMAGE_TAG}}" >> $GITHUB_OUTPUT
        
  analyze:
    name: Analyze
    runs-on: ubuntu-latest    
    needs: variable_substitution
    container:
      image: ${{ needs.variable_substitution.outputs.image }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read
    steps:
# Checks out your repository under $GITHUB_WORKSPACE, so that your job can access it.
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - uses: microsoft/ApplicationInspector-Action@v1.0.1
      with:
        location-to-scan: ./Core/Src
        output-format: text
        
    - uses: actions/upload-artifact@v3.1.2
      with:
        name: AppInspectorResults
        path: AppInspectorResults.text
        
#    - name: Run linters
#      uses: wearerequired/lint-action@v2.3.0
#      with:
#        clang_format: true
#        working-directory:: ./Core/Src/
