name: "CI Testing"

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
# Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:
  
env:
  REGISTRY: ghcr.io
  REPO_NAME: ${{ github.event.repository.name }}
  USER_NAME: ${{ github.actor }}
  VERSION: "latest"
  IMAGE_TAG: ${REGISTRY,,}"/"${USER_NAME,,}"/"${REPO_NAME,,}":"${VERSION,,}
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  variable_substitution:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.set_image.outputs.image }}
    steps:
      - id: set_image
        run: echo "image=${{env.IMAGE_TAG}}" >> $GITHUB_OUTPUT
        
  test:
    name: Testing
    runs-on: ubuntu-latest    
    needs: variable_substitution
    container:
      image: ${{ needs.variable_substitution.outputs.image }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read
    steps:
# Checks out your repository under $GITHUB_WORKSPACE, so that your job can access it.
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Run the Makefile and Build the Project
      run: make
      
# CppCheck analysis task
    - name: cppcheck
      uses: deep5050/cppcheck-action@v3.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN}}
        exclude_check: ./Drivers
        force_language: c
        max_ctu_depth: 8
        output_file: CppCheckReport.txt
        
    - uses: actions/upload-artifact@v3
      with:
        name: CppCheckReport
        path: ./CppCheckReport.txt
        
    - name: ApplicationInspector
      uses: microsoft/ApplicationInspector-Action@v1.0.1
    
    - uses: actions/upload-artifact@v3.1.2
      with:
        name: AppInspectorResults
        path: AppInspectorResults.json
        
    - name: lint
      uses: devblackops/github-action-psscriptanalyzer@master
      with:
        repoToken: ${{ secrets.GITHUB_TOKEN }}
        
# Report generating task
#    - name: publish report    
#      uses: mikeal/publish-to-github-action@master
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        BRANCH_NAME: 'dev' # your branch name goes here
          
#    - name: 'Preparing Cmock -environment'
#      uses: actions/checkout@v3
#      with:
#        repository: ThrowTheSwitch/CMock
#        
#    - run: ls
#    - name: Run Tests
#      run: |
#        cd test
#        rake
#      working-directory: ./test

      
