name: Versioning

on:
  push:
    branches:
      - 'versioning'
  workflow_dispatch:
  
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  
jobs:
  versioning:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Run versioning script file
      run: |
         chmod +x ./scripts/versioning.sh
         ./scripts/versioning.sh
      shell: bash

    - id: git_tag
      run: echo "GIT_TAG=`echo $(git describe --tags)`" >> $GITHUB_ENV
    - name: Check output
      run: |
        echo $RELEASE_VERSION
        echo ${{ steps.git_tag.outputs.GIT_TAG }}
          
