name: Versioning

on:
  push:
    branches:
      - 'versioning'
  pull_request:
    branches:
      - 'versioning'
  workflow_dispatch:
  
env:
  REGISTRY: ghcr.io
  REPO_NAME: ${{ github.event.repository.name }}
  USER_NAME: ${{ github.actor }}
  ORG_NAME: ${{ github.repository_owner }}
  VERSION: "latest"
  IMAGE_TAG: ${REGISTRY,,}"/"${ORG_NAME,,}"/"${REPO_NAME,,}":"${VERSION,,}
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  
jobs:
  versioning:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Calculate Semantic Versioning
      uses: paulhatch/semantic-version@v5.3.0
      id: semantic_versioning
      with:
        tag_prefix: "v"
        major_pattern: "(MAJOR)"
        minor_pattern: "(MINOR)"
        version_format: "${major}.${minor}.${patch}-${BRANCH_NAME}.${increment}"
        user_format_type: "json"
      env: 
        BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
    - run: echo ${GITHUB_REF#refs/heads/}
