name: Versioning

on:
  push:
    branches:
      - 'versioning'
  workflow_dispatch:
  
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  
jobs:
  versioning:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Calculate Semantic Versioning
      uses: paulhatch/semantic-version@v5.3.0
      id: semantic_versioning
      with:
        tag_prefix: "v"
        major_pattern: "(MAJOR)"
        major_regexp_flags: ""
        minor_pattern: "(MINOR)"
        minor_regexp_flags: ""
        version_format: "${major}.${minor}.${patch}-${{ env.BRANCH_NAME }}.${increment}"
        search_commit_body: true
        enable_prerelease_mode: true
        
