name: Versioning

on:
  push:
    branches:
      - 'versioning'
  pull_request:
    branches:
      - 'versioning'
  workflow_dispatch:
  
# The IMAGE_TAG sets the docker image name, it must be lowercase the ,, convert to lowercase
env:
  REGISTRY: ghcr.io
  REPO_NAME: ${{ github.event.repository.name }}
  USER_NAME: ${{ github.actor }}
  ORG_NAME: ${{ github.repository_owner }}
  VERSION: "latest"
  IMAGE_TAG: ${REGISTRY,,}"/"${ORG_NAME,,}"/"${REPO_NAME,,}":"${VERSION,,}

jobs:
  versioning:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Calculate Semantic Versioning
      uses: paulhatch/semantic-version@v5.3.0
      with:
        tag_prefix: "v"
        major_pattern: "(MAJOR)"
        minor_pattern: "(MINOR)"
        version_format: "${major}.${minor}.${patch}-${{ steps.extract-branch.outputs.branch-name }}.${increment}"

