name: Versioning

on:
  push:
    branches:
      - 'versioning'
  workflow_dispatch:
  
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  
jobs:
  versioning:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Run versioning script file
      run: |
         chmod +x ./scripts/versioning.sh
         ./scripts/versioning.sh
      shell: bash
